stages:
  - build
  - test
  - scan
  - deploy

variables:
  PROJ_FILE_PATH: "pom.xml"
  SONAR_SCANNER_OPTIONS: |
    -Dsonar.dependencyCheck.xmlReportPath=dependency-check/dependency-check-report.xml
    -Dsonar.dependencyCheck.jsonReportPath=dependency-check/dependency-check-report.json
    -Dsonar.dependencyCheck.htmlReportPath=dependency-check/dependency-check-report.html
  OAUTH_PROXY_IMAGE_TAG: "v7-update1"
  # disabled by default, to avoid issues when not defined
  ENABLE_OAUTH_PROXY: "false"
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  image: maven:latest

build:
  stage: build
  image: ${image}
  script:
    - cd "${PROJECT_ROOT_DIR}"
    #    - rm -Force target/*
    - mvn package -s settings.xml
  cache:
    # cache target folder for pipeline performances
    policy: pull-push
    untracked: false
    paths:
      - $PROJECT_ROOT_DIR/target/
  artifacts:
    paths:
      - $PROJECT_ROOT_DIR/target/*.jar
